image: fedora/38
arch: x86_64
packages:
  - emacs
sources:
  - git@git.sr.ht:~willvaughn/emacs-0x0
tasks:
  - test: |
      cd emacs-0x0
      emacs -batch -l ert -l 0x0.el -l 0x0-test.el -eval "(ert-run-tests-batch-and-exit '(not (tag :integration)))"
